application: gotwigglet
version: 1
runtime: go
api_version: go1

handlers:
- url: /
  static_files: src/main/webapp/index.html
  upload: src/main/webapp/index.html

- url: /scripts
  static_dir: src/main/webapp/scripts

- url: /v1.*
  script: _go_app