application: gotwigglet
version: 1
runtime: go
api_version: go1

handlers:
- url: /
  static_files: index.html
  upload: index.html

- url: /static
  static_dir: static

- url: /v1.*
  script: _go_app