application: gotwigglet
version: 1
runtime: go
api_version: go1

handlers:
- url: /
  static_files: index.html
  upload: index.html

- url: /v1.*
  script: _go_app

- url: /.*
  static_dir: /src/main/webapp